apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  ports:
    - port: 21
      targetPort: 21
      nodePort: 21
      name: ftps
    - port: 30021
      targetPort: 30021
      nodePort: 30021
      name: ftps-pasv
  selector: 
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.49.14
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - image: service_ftps
        imagePullPolicy: Never
        name: ftps
