apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 5000
      protocol: TCP
  selector:
    app: phpmyadmin
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pma-pv-claim
  labels:
    app: phpmyadmin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
        tier: frontend
    spec:
      containers:
      - image: service_phpmyadmin
        imagePullPolicy: Never
        name: phpmyadmin
        ports:
        - containerPort: 5000
          name: phpmyadmin
        volumeMounts:
        - name: phpmyadmin-persistent-storage
          mountPath: /var/www/phpmyadmin
      volumes:
      - name: phpmyadmin-persistent-storage
        persistentVolumeClaim:
          claimName: pma-pv-claim
